### ISSUE TITLE
cursed recipes in JEI

### ISSUE THREAD

**Issue by VamenSol1dnik** [Craftjakob/Enderite-CJ-Edition#13]
some recipes of items have dubpicated by parts
![image](https://github.com/user-attachments/assets/3924637b-6fca-470a-9644-466d39b320e6)
![image](https://github.com/user-attachments/assets/ea9fe506-c885-4361-814e-a68a66f4a839)

**Comment by VamenSol1dnik** [comment]
there is newest version of mode

**Comment by Craftjakob** [comment]
The reason why it displayed it like that is, that you don't have Gilded Netherite Installed.
I will add a Tooltip, that says you need to install Gilded Netherite, to craft these things.

Why I cannot remove the recipes, if the mod is not installed?
The only way is through Conditions, but conditions are only in Forge and NeoForge.

Why can I not remove the recipes and add these recipes to Gilded Netherite?
Because then you have this issue with Gilded Netherite.

**Comment by VamenSol1dnik** [comment]
will Enderite debris take Fortune for getting more Raw Enderite? And why doesn`t Staff of Farmer in Gobber mode take grow The Clusters in Ender Geodes?

In Addiction, texture for pressed End Stone is like vanilla End stone variant. That can be changed with, for example, gamma or brightness (so darker texture or specific collour)

**Comment by Craftjakob** [comment]
I have removed that you can get more Raw Enderite with Fortune and Ancient Debris does also not drop more, but that's because you get the block.
Yes, a more significant texture for Hardened End Stone would be good.

I don't understand this:
And why doesn`t Staff of Farmer in Gobber mode take grow The Clusters in Ender Geodes?

**Comment by VamenSol1dnik** [comment]
![image](https://github.com/user-attachments/assets/11775763-ffe3-4b1e-b665-70b13176732c)
i have downloaded Gilded Netherite but...

**Comment by Craftjakob** [comment]
In which version do you have this issue?
Because in 1.21.1 does everything work.
![image](https://github.com/user-attachments/assets/4097c23c-b556-4507-ad70-c07791aad72e)

**Comment by VamenSol1dnik** [comment]
1.21
Mod Gobber has different medalions, rings, staffs.
For example. Staff of Farm grows up plants, including Amethyst clusters in main hand in range 10 - 14 blocks. On right-click, you can gain drops and seeds will replace. Ender Geode is equal of Amethyst Geode, so that Staff should work

**Comment by Craftjakob** [comment]
The Staff does now work with Budding Ender Crystals
Problem was, that the staffs checks for an instance of BuddingAmethystBlock and not AmethystBlock.
The best way would be to use tags, but I haven't found any. So now my blocks extends BuddingAmethystBlock.

**Comment by Craftjakob** [comment]
I also have changed the Hardened End Stone texture a little bit more.

**Comment by VamenSol1dnik** [comment]
You can connect with developer of Gobber, in discord server Pughland 
https://www.curseforge.com/minecraft/mc-mods/gobber-fabric
![image](https://github.com/user-attachments/assets/5fd9b023-0043-47ec-85ca-4a320ad9be23)
bottom of page

**Comment by VamenSol1dnik** [comment]
Where should i find upgrade of Enderite?

**Comment by Craftjakob** [comment]
It does not matter, I am closing it.
