### ISSUE TITLE
not compatible with End's Phantasm mod

### ISSUE THREAD

**Issue by btd6player27** [Craftjakob/Enderite-CJ-Edition#14]
When i try to generate a new world while having both the Enderite armor mod and the End Phansasm mod for minecraft 1.21.1, I get an error during world generation saying " java.lang.illegalstateexception: end size is 356 is less than fixed size 357" .

**Comment by Craftjakob** [comment]
![image](https://github.com/user-attachments/assets/d638db1f-f1db-43ca-9fc0-0c9f9ad77d79)

It's not happening in my test launch in NeoForge 1.21.1.
And I think it's not a problem with my Mod, maybe with some other mod, because of the "end size", I do not change something like that, I only add a few features, but I do not change the world generation.

You could remove all mods and add one after one back to the modpack, so you can find the mod, which causes this issue. And maybe it's a problem with the End Phansasm mod, because this Mod is in Beta.

**Comment by btd6player27** [comment]
got it. it may be due to the fact that i have almost 200 mods in my mod pack, but all i know is that your enderite mod was working just fine, then i added end phantasm, got that error. if i removed either the end phantasm mod or the enderite mod, the game works just fine. i tried talking to the creators of end phantasm and they said they're unable to do anything because enderite mod is closed source so i figured it just tell you about it and see if anything could be done
